# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"5\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\r\n\x05index\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\xb0\x01\n\x10\x41ppendEntriesReq\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\x12\x14\n\x0cleader_lease\x18\x07 \x01(\x03\"N\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\"c\n\x0eRequestVoteReq\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"O\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x14\n\x0cleader_lease\x18\x03 \x01(\x03\"\x15\n\x06GetReq\x12\x0b\n\x03key\x18\x01 \x01(\t\"@\n\x0bGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\x05\"$\n\x06SetReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"1\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x32\xdc\x01\n\x04Raft\x12\x44\n\rAppendEntries\x12\x16.raft.AppendEntriesReq\x1a\x1b.raft.AppendEntriesResponse\x12>\n\x0bRequestVote\x12\x14.raft.RequestVoteReq\x1a\x19.raft.RequestVoteResponse\x12&\n\x03Get\x12\x0c.raft.GetReq\x1a\x11.raft.GetResponse\x12&\n\x03Set\x12\x0c.raft.SetReq\x1a\x11.raft.SetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=73
  _globals['_APPENDENTRIESREQ']._serialized_start=76
  _globals['_APPENDENTRIESREQ']._serialized_end=252
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=254
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=332
  _globals['_REQUESTVOTEREQ']._serialized_start=334
  _globals['_REQUESTVOTEREQ']._serialized_end=433
  _globals['_REQUESTVOTERESPONSE']._serialized_start=435
  _globals['_REQUESTVOTERESPONSE']._serialized_end=514
  _globals['_GETREQ']._serialized_start=516
  _globals['_GETREQ']._serialized_end=537
  _globals['_GETRESPONSE']._serialized_start=539
  _globals['_GETRESPONSE']._serialized_end=603
  _globals['_SETREQ']._serialized_start=605
  _globals['_SETREQ']._serialized_end=641
  _globals['_SETRESPONSE']._serialized_start=643
  _globals['_SETRESPONSE']._serialized_end=692
  _globals['_RAFT']._serialized_start=695
  _globals['_RAFT']._serialized_end=915
# @@protoc_insertion_point(module_scope)
